version: "2"

volumes:
  mongodb: {}

services:
  
  nginx:
    build:
      dockerfile: dockerfiles/nginx/Dockerfile
      context: .
    ports:
      - "80:80"
      # If you want to support TLS, enable port 443 and edit dockerfiles/nginx/nginx.conf
      #- "443:443"
    depends_on:
      - swift
      - mongo_express
    env_file:
      - "./env/admin.env"
    restart: always

  swift:
    build:
      dockerfile: dockerfiles/swift/Dockerfile
      context: .
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo
    volumes:
      - "mongodb:/data/db"
    restart: always

  mongo_express:
    image: mongo-express
    environment:
      - ME_CONFIG_SITE_BASEURL=/admin/mongo-express/
    restart: always